### PR TITLE
need fast partitioner for nth_element

### PR DESCRIPTION
**Pull request by ecrypa**
I tested some more approaches to `nth_element`. The compilation time is dominated by the comparison of elements with the pivot in order to create the partitions. The original version (v0) is slow on GCC 9 because GCC 9 dislikes the pack expansion of the form
```
join<if_<comp<vals, piv>, list<vals>, list<>>...>
```
An obvious alternative is v1, which is based on `metal::partition`. I think that we can make it SFINAE-friendly in analogy to `metal::min_element`. However, the current implementation of `metal::partition` uses `metal::replace_if` once for the lo partition and once more for the non-lo partition. As an optimization, v2 creates both partitions at once by using a [custom 20-line partitioner](https://github.com/brunocodutra/metal/pull/115/files#diff-d77f2ed31417a4569b562d1540f6dbcbR20). It is twice as fast on both [Clang 9](https://ecrypa.github.io/metal-benchmark/nth_element_clang9/) and [GCC 9](https://ecrypa.github.io/metal-benchmark/nth_element_gcc9/). I suggest to choose v2.

Do you agree that the speedup of v2 over v1 is worth the extra code?

If yes: should we change `metal::partition`, or should `metal::nth_element` come with its own custom partitioner?

### CODE REVIEW

**Comment by brunocodutra** [comment]
> should we change metal::partition, or should metal::nth_element come with its own custom partitioner?

If we find a faster implementation we should definitely make use of it in `metal::partition`. In this case I'd also consider rewriting `metal::copy_if` and `metal::remove_if` in terms of partition, to avoid the [`metal::bind`](https://github.com/brunocodutra/metal/blob/master/include/metal/list/copy_if.hpp#L41) which we know is a performance killer.

> Do you agree that the speedup of v2 over v1 is worth the extra code?

I think it's worth it considering it's not that complex and the fact `metal::partition` and possibly also `metal::copy_if` would benefit from it.

**Comment by ecrypa** [comment]
I just learned that my browser can save [metabench.ch graphs](http://metaben.ch/type/g++-7/partition/index.html) like just fine. I have to save every algorithm and compiler individually, though (for later comparison).

Do you know a "hidden" possibility to view older builds of metabench.ch?

**Comment by brunocodutra** [comment]
You mean like saving a baseline to compare against? It's been a long time, but I don't think this feature exists built in. What used to do was to add a fake library which pointed to a hard coded path on my machine where it could find my workspace instead of downloading headers from git. This way it benchmarks this fake library against metal (and other libs) from github. 

Is that what you're looking for?

**Comment by ecrypa** [comment]
> You mean like saving a baseline to compare against?

Exactly.

> What used to do was to add a fake library which pointed to a hard coded path on my machine [...]

Yes, I am using exactly the same setup for my benchmarks.

> Is that what you're looking for?

metaben.ch has some advantages over my current setup:
* plenty of Clang and GCC versions
* testing in an established environment (hardware, reliable metabench setup, ...)
* I can continue to use my computer without affecting the measurements

The data from earlier builds exist, and their reuse is the simplest option that came to my mind. Just wanted to make sure that I am not missing a secret "timetravel" option of metaben.ch.

**Comment by brunocodutra** [comment]
@ecrypa I've recently migrated away from Travis and Appveyor to Github actions (#127) and the turnaround time is much quicker now. Just thought I should let you know.

**Comment by ecrypa** [comment]
> @ecrypa I've recently migrated away from Travis and Appveyor to Github actions (#127) and the turnaround time is much quicker now.

Thanks for your hint. I tested it, and it is much better.

**Comment by ecrypa** [comment]
Closing in favor of #124.

**Pull request closed without merging**
